### PR TITLE
Version bump to 3.5.0

### PR DESCRIPTION
**Pull request by ericmjl**

### CODE REVIEW

**Review by ericdill — APPROVED** [review]
Hi @ericmjl -- Theoretically you could make this a noarch package if you want to by adding to the build section:
```yaml
    noarch: python
```

This has the advantage of not having to hit travis-ci for builds and only needing to build *one* package for each build. Up to you 😁

**Comment by ericmjl** [comment]
Hi @ericdill! just followed up with that recommendation!

**Comment by ericdill** [comment]
I think you need to rerender after making the package noarch. Sorry for not mentioning this earlier

**Comment by ericdill** [comment]
I just saw that you're adding yourself to as a maintainer. Thanks for sharing in the maintenance!

**Comment by ericdill** [comment]
Ok great. 310f541 did what I was hoping it would do a drop the other CI services

**Comment by ericdill** [comment]
now we just have to wait on circle-ci. But this does mean you'll need to use conda >=4.3 to install this package. I hope that isn't an issue for your use case!

**Comment by ericmjl** [comment]
Ping @ericdill it's done! No problem for my use case.

**Review by ericdill — APPROVED** [review]
LGTM. Let me know when you think this is ready to merge.

**Comment by ericdill** [comment]
Looks like we were writing to each other at the same time :) Merged!

**Comment by ericmjl** [comment]
Thank you! :smile:

**Pull request merged**
